query Securities {
	securities @list(name: "All_Securities") {
		id
		displayName
		identifiers {
			kind
			value
		}
		listings {
			id
			ticker
			exchange
			currency
			quoteProvider
			latestQuote {
				time
				price {
					amount
					currency
				}
			}
		}
	}
}
