// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package persistence

import (
	"database/sql"
	"time"

	currency "github.com/oxisto/money-gopher/currency"
	"github.com/oxisto/money-gopher/portfolio/events"
)

type BankAccount struct {
	// ID is the primary identifier for a bank account.
	ID string
	// DisplayName is the human-readable name of the bank account.
	DisplayName string
}

// ListedSecurity represents a security that is listed on a particular exchange.
type ListedSecurity struct {
	// SecurityID is the ID of the security.
	SecurityID string
	// Ticker is the symbol used to identify the security on the exchange.
	Ticker string
	// Currency is the currency in which the security is traded.
	Currency string
	// LatestQuote is the latest quote for the security as a [currency.Currency].
	LatestQuote *currency.Currency
	// LatestQuoteTimestamp is the timestamp of the latest quote.
	LatestQuoteTimestamp sql.NullTime
}

type Portfolio struct {
	// ID is the primary identifier for a portfolio.
	ID string
	// DisplayName is the human-readable name of the portfolio.
	DisplayName string
	// BankAccountID is the ID of the bank account that holds the portfolio.
	BankAccountID string
}

type PortfolioEvent struct {
	ID          string
	Type        events.PortfolioEventType
	Time        time.Time
	PortfolioID string
	SecurityID  string
	Amount      float64
	Price       *currency.Currency
	Fees        *currency.Currency
	Taxes       *currency.Currency
}

// Security represents a security that can be traded on an exchange.
type Security struct {
	// ID is the primary identifier for a security.
	ID string
	// DisplayName is the human-readable name of the security.
	DisplayName string
	// QuoteProvider is the name of the provider that provides quotes for this security.
	QuoteProvider sql.NullString
}
