// Code generated by "stringer -linecomment -type=AccountType -output=type_string.go"; DO NOT EDIT.

package accounts

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AccountTypeBrokerage-1]
	_ = x[AccountTypeBank-2]
	_ = x[AccountTypeLoan-3]
}

const _AccountType_name = "BROKERAGEBANKLOAN"

var _AccountType_index = [...]uint8{0, 9, 13, 17}

func (i AccountType) String() string {
	i -= 1
	if i < 0 || i >= AccountType(len(_AccountType_index)-1) {
		return "AccountType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AccountType_name[_AccountType_index[i]:_AccountType_index[i+1]]
}
