import Nav from "@/components/nav";
import Sidebar from "@/components/sidebar/sidebar";
import { classNames } from "@/lib/util";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { Inter } from "./fonts";
import { Suspense } from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full bg-gray-100">
      <body className={classNames(Inter.className, "h-full")}>
        <Nav
          mobileSidebar={<Sidebar isDesktop={false} />}
          desktopSidebar={<Sidebar isDesktop={true} />}
        />

        <main className="py-10 lg:pl-72">
          <div className="px-4 sm:px-6 lg:px-8">
            <NextIntlClientProvider>
              <Suspense>{children}</Suspense>
            </NextIntlClientProvider>
          </div>
        </main>
      </body>
    </html>
  );
}
