query Imports {
	documents {
		id
		filename
		state
		detectedBank
		error
		transactionDate
		suggestedCashAccount {
			id
			displayName
			currency
		}
		stagedTransactions {
			id
			type
			time
			units
			price {
				amount
				currency
			}
			fees {
				amount
				currency
			}
			taxes {
				amount
				currency
			}
			cashDelta {
				amount
				currency
			}
			currency
			securityHint
			isin
			security {
				id
				displayName
			}
		}
	}
	portfolios {
		id
		displayName
	}
	cashAccounts {
		id
		displayName
		currency
		iban
	}
	securities {
		id
		displayName
	}
}
