// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cash_accounts.sql

package persistence

import (
	"context"
	"database/sql"
)

const createCashAccount = `-- name: CreateCashAccount :one
INSERT INTO
    cash_accounts (id, user_id, display_name, currency)
VALUES
    (?, ?, ?, ?) RETURNING id, user_id, display_name, currency, created_at
`

type CreateCashAccountParams struct {
	ID          string
	UserID      string
	DisplayName string
	Currency    string
}

func (q *Queries) CreateCashAccount(ctx context.Context, arg CreateCashAccountParams) (*CashAccount, error) {
	row := q.db.QueryRowContext(ctx, createCashAccount,
		arg.ID,
		arg.UserID,
		arg.DisplayName,
		arg.Currency,
	)
	var i CashAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Currency,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteCashAccount = `-- name: DeleteCashAccount :execrows
DELETE FROM cash_accounts
WHERE
    id = ?
    AND user_id = ?
`

type DeleteCashAccountParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteCashAccount(ctx context.Context, arg DeleteCashAccountParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCashAccount, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCashAccount = `-- name: GetCashAccount :one
SELECT
    id, user_id, display_name, currency, created_at
FROM
    cash_accounts
WHERE
    id = ?
    AND user_id = ?
`

type GetCashAccountParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetCashAccount(ctx context.Context, arg GetCashAccountParams) (*CashAccount, error) {
	row := q.db.QueryRowContext(ctx, getCashAccount, arg.ID, arg.UserID)
	var i CashAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Currency,
		&i.CreatedAt,
	)
	return &i, err
}

const getCashAccountBalance = `-- name: GetCashAccountBalance :one
SELECT
    CAST(COALESCE(SUM(cash_delta), 0) AS INTEGER) AS balance
FROM
    transactions
WHERE
    cash_account_id = ?
`

func (q *Queries) GetCashAccountBalance(ctx context.Context, cashAccountID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCashAccountBalance, cashAccountID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const listCashAccounts = `-- name: ListCashAccounts :many
SELECT
    id, user_id, display_name, currency, created_at
FROM
    cash_accounts
WHERE
    user_id = ?
ORDER BY
    display_name
`

func (q *Queries) ListCashAccounts(ctx context.Context, userID string) ([]*CashAccount, error) {
	rows, err := q.db.QueryContext(ctx, listCashAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CashAccount
	for rows.Next() {
		var i CashAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCashAccount = `-- name: UpdateCashAccount :one
UPDATE cash_accounts
SET
    display_name = ?
WHERE
    id = ?
    AND user_id = ? RETURNING id, user_id, display_name, currency, created_at
`

type UpdateCashAccountParams struct {
	DisplayName string
	ID          string
	UserID      string
}

func (q *Queries) UpdateCashAccount(ctx context.Context, arg UpdateCashAccountParams) (*CashAccount, error) {
	row := q.db.QueryRowContext(ctx, updateCashAccount, arg.DisplayName, arg.ID, arg.UserID)
	var i CashAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Currency,
		&i.CreatedAt,
	)
	return &i, err
}
