// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: documents.sql

package persistence

import (
	"context"
	"database/sql"
	"time"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO
    documents (id, person_id, filename, content_type, data)
VALUES
    (?, ?, ?, ?, ?) RETURNING id, user_id, filename, content_type, data, state, detected_bank, extracted_text, error, settlement_iban, transaction_date, created_at, person_id
`

type CreateDocumentParams struct {
	ID          string
	PersonID    string
	Filename    string
	ContentType string
	Data        []byte
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (*Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.ID,
		arg.PersonID,
		arg.Filename,
		arg.ContentType,
		arg.Data,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Filename,
		&i.ContentType,
		&i.Data,
		&i.State,
		&i.DetectedBank,
		&i.ExtractedText,
		&i.Error,
		&i.SettlementIban,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.PersonID,
	)
	return &i, err
}

const createStagedTransaction = `-- name: CreateStagedTransaction :one
INSERT INTO
    staged_transactions (
        id,
        document_id,
        type,
        time,
        units,
        price,
        fees,
        taxes,
        cash_delta,
        currency,
        security_hint,
        isin,
        security_id
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, document_id, type, time, units, price, fees, taxes, cash_delta, currency, security_hint, isin, security_id, created_at
`

type CreateStagedTransactionParams struct {
	ID           string
	DocumentID   string
	Type         string
	Time         time.Time
	Units        float64
	Price        sql.NullInt64
	Fees         int64
	Taxes        int64
	CashDelta    int64
	Currency     string
	SecurityHint sql.NullString
	Isin         sql.NullString
	SecurityID   sql.NullString
}

func (q *Queries) CreateStagedTransaction(ctx context.Context, arg CreateStagedTransactionParams) (*StagedTransaction, error) {
	row := q.db.QueryRowContext(ctx, createStagedTransaction,
		arg.ID,
		arg.DocumentID,
		arg.Type,
		arg.Time,
		arg.Units,
		arg.Price,
		arg.Fees,
		arg.Taxes,
		arg.CashDelta,
		arg.Currency,
		arg.SecurityHint,
		arg.Isin,
		arg.SecurityID,
	)
	var i StagedTransaction
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Type,
		&i.Time,
		&i.Units,
		&i.Price,
		&i.Fees,
		&i.Taxes,
		&i.CashDelta,
		&i.Currency,
		&i.SecurityHint,
		&i.Isin,
		&i.SecurityID,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteDocument = `-- name: DeleteDocument :execrows
DELETE FROM documents
WHERE
    id = ?
    AND person_id = ?
`

type DeleteDocumentParams struct {
	ID       string
	PersonID string
}

func (q *Queries) DeleteDocument(ctx context.Context, arg DeleteDocumentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDocument, arg.ID, arg.PersonID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteStagedTransactions = `-- name: DeleteStagedTransactions :exec
DELETE FROM staged_transactions
WHERE
    document_id = ?
`

func (q *Queries) DeleteStagedTransactions(ctx context.Context, documentID string) error {
	_, err := q.db.ExecContext(ctx, deleteStagedTransactions, documentID)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT
    id, user_id, filename, content_type, data, state, detected_bank, extracted_text, error, settlement_iban, transaction_date, created_at, person_id
FROM
    documents
WHERE
    id = ?
    AND person_id = ?
`

type GetDocumentParams struct {
	ID       string
	PersonID string
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (*Document, error) {
	row := q.db.QueryRowContext(ctx, getDocument, arg.ID, arg.PersonID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Filename,
		&i.ContentType,
		&i.Data,
		&i.State,
		&i.DetectedBank,
		&i.ExtractedText,
		&i.Error,
		&i.SettlementIban,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.PersonID,
	)
	return &i, err
}

const getStagedTransaction = `-- name: GetStagedTransaction :one
SELECT
    id, document_id, type, time, units, price, fees, taxes, cash_delta, currency, security_hint, isin, security_id, created_at
FROM
    staged_transactions
WHERE
    id = ?
`

func (q *Queries) GetStagedTransaction(ctx context.Context, id string) (*StagedTransaction, error) {
	row := q.db.QueryRowContext(ctx, getStagedTransaction, id)
	var i StagedTransaction
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Type,
		&i.Time,
		&i.Units,
		&i.Price,
		&i.Fees,
		&i.Taxes,
		&i.CashDelta,
		&i.Currency,
		&i.SecurityHint,
		&i.Isin,
		&i.SecurityID,
		&i.CreatedAt,
	)
	return &i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT
    id, user_id, filename, content_type, data, state, detected_bank, extracted_text, error, settlement_iban, transaction_date, created_at, person_id
FROM
    documents
WHERE
    person_id = ?
ORDER BY
    transaction_date ASC NULLS LAST, created_at ASC
`

func (q *Queries) ListDocuments(ctx context.Context, personID string) ([]*Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Filename,
			&i.ContentType,
			&i.Data,
			&i.State,
			&i.DetectedBank,
			&i.ExtractedText,
			&i.Error,
			&i.SettlementIban,
			&i.TransactionDate,
			&i.CreatedAt,
			&i.PersonID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByState = `-- name: ListDocumentsByState :many
SELECT
    id, user_id, filename, content_type, data, state, detected_bank, extracted_text, error, settlement_iban, transaction_date, created_at, person_id
FROM
    documents
WHERE
    person_id = ?
    AND state = ?
ORDER BY
    transaction_date ASC NULLS LAST, created_at ASC
`

type ListDocumentsByStateParams struct {
	PersonID string
	State    string
}

func (q *Queries) ListDocumentsByState(ctx context.Context, arg ListDocumentsByStateParams) ([]*Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsByState, arg.PersonID, arg.State)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Filename,
			&i.ContentType,
			&i.Data,
			&i.State,
			&i.DetectedBank,
			&i.ExtractedText,
			&i.Error,
			&i.SettlementIban,
			&i.TransactionDate,
			&i.CreatedAt,
			&i.PersonID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStagedTransactions = `-- name: ListStagedTransactions :many
SELECT
    id, document_id, type, time, units, price, fees, taxes, cash_delta, currency, security_hint, isin, security_id, created_at
FROM
    staged_transactions
WHERE
    document_id = ?
ORDER BY
    time
`

func (q *Queries) ListStagedTransactions(ctx context.Context, documentID string) ([]*StagedTransaction, error) {
	rows, err := q.db.QueryContext(ctx, listStagedTransactions, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*StagedTransaction
	for rows.Next() {
		var i StagedTransaction
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Type,
			&i.Time,
			&i.Units,
			&i.Price,
			&i.Fees,
			&i.Taxes,
			&i.CashDelta,
			&i.Currency,
			&i.SecurityHint,
			&i.Isin,
			&i.SecurityID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentState = `-- name: UpdateDocumentState :one
UPDATE documents
SET
    state = ?,
    detected_bank = ?,
    extracted_text = ?,
    error = ?,
    settlement_iban = ?,
    transaction_date = ?
WHERE
    id = ? RETURNING id, user_id, filename, content_type, data, state, detected_bank, extracted_text, error, settlement_iban, transaction_date, created_at, person_id
`

type UpdateDocumentStateParams struct {
	State           string
	DetectedBank    sql.NullString
	ExtractedText   sql.NullString
	Error           sql.NullString
	SettlementIban  sql.NullString
	TransactionDate sql.NullTime
	ID              string
}

func (q *Queries) UpdateDocumentState(ctx context.Context, arg UpdateDocumentStateParams) (*Document, error) {
	row := q.db.QueryRowContext(ctx, updateDocumentState,
		arg.State,
		arg.DetectedBank,
		arg.ExtractedText,
		arg.Error,
		arg.SettlementIban,
		arg.TransactionDate,
		arg.ID,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Filename,
		&i.ContentType,
		&i.Data,
		&i.State,
		&i.DetectedBank,
		&i.ExtractedText,
		&i.Error,
		&i.SettlementIban,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.PersonID,
	)
	return &i, err
}
