// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package persistence

import (
	"time"
)

type User struct {
	ID          string
	Issuer      string
	Subject     string
	DisplayName string
	CreatedAt   time.Time
}
