// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package persistence

import (
	"database/sql"
	"time"
)

type CashAccount struct {
	ID          string
	PersonID    string
	DisplayName string
	Currency    string
	Iban        sql.NullString
	CreatedAt   time.Time
}

type Document struct {
	ID              string
	PersonID        string
	Filename        string
	ContentType     string
	Data            []byte
	State           string
	DetectedBank    sql.NullString
	ExtractedText   sql.NullString
	Error           sql.NullString
	SettlementIban  sql.NullString
	TransactionDate sql.NullTime
	CreatedAt       time.Time
}

// Listing is a security listed on a particular exchange.
type Listing struct {
	ID            string
	SecurityID    string
	Exchange      sql.NullString
	Ticker        string
	Currency      string
	QuoteProvider sql.NullString
}

type Person struct {
	ID          string
	DisplayName string
	CreatedAt   time.Time
}

type Portfolio struct {
	ID            string
	PersonID      string
	DisplayName   string
	CashAccountID string
	CreatedAt     time.Time
}

// Quote is one price observation for a listing.
type Quote struct {
	ListingID string
	Time      time.Time
	Price     int64
}

// Security is a tradable security, shared across all users.
type Security struct {
	ID          string
	DisplayName string
}

// SecurityIdentifier maps an external identifier (ISIN, WKN, …) to a security.
type SecurityIdentifier struct {
	SecurityID string
	Kind       string
	Value      string
}

type Session struct {
	ID        string
	UserID    string
	CreatedAt time.Time
	ExpiresAt time.Time
	PersonID  sql.NullString
}

// StagedTransaction is a parsed transaction awaiting user review.
type StagedTransaction struct {
	ID           string
	DocumentID   string
	Type         string
	Time         time.Time
	Units        float64
	Price        sql.NullInt64
	Fees         int64
	Taxes        int64
	CashDelta    int64
	Currency     string
	SecurityHint sql.NullString
	Isin         sql.NullString
	SecurityID   sql.NullString
	CreatedAt    time.Time
}

// Transaction is a typed portfolio/cash event.
type Transaction struct {
	ID            string
	Type          string
	Time          time.Time
	PortfolioID   sql.NullString
	SecurityID    sql.NullString
	CashAccountID sql.NullString
	Units         float64
	Price         sql.NullInt64
	Fees          int64
	Taxes         int64
	CashDelta     int64
	Currency      string
	Source        string
	CreatedAt     time.Time
}

// User is a person using money-gopher, provisioned on first OIDC login.
type User struct {
	ID          string
	Issuer      string
	Subject     string
	DisplayName string
	CreatedAt   time.Time
}

type UserPersonAccess struct {
	UserID   string
	PersonID string
}
