// Package persistence provides access to the SQLite database of moneyd. The
// typed query code is generated by sqlc from internal/persistence/sql; run
// `go generate ./...` after changing the schema or queries.
package persistence

import (
	"context"
	"database/sql"
	"embed"
	"fmt"

	"github.com/pressly/goose/v3"
	_ "modernc.org/sqlite"
)

//go:generate sqlc generate -f ../../sqlc.yaml

//go:embed sql/migrations/*.sql
var migrations embed.FS

// DB wraps the generated queries together with the underlying connection.
type DB struct {
	*Queries

	conn *sql.DB
}

// OpenDB opens the SQLite database at path (created if missing) and applies
// all pending migrations. Use ":memory:" for an ephemeral database in tests.
func OpenDB(path string) (*DB, error) {
	// _time_format=sqlite makes the driver store time.Time values as
	// "2006-01-02 15:04:05.999999999-07:00" instead of Go's default
	// time.Time.String() — parseable by SQLite's datetime functions and,
	// together with storing all times in UTC, lexicographically sortable.
	conn, err := sql.Open("sqlite", path+"?_pragma=foreign_keys(1)&_pragma=journal_mode(WAL)&_time_format=sqlite")
	if err != nil {
		return nil, fmt.Errorf("could not open database: %w", err)
	}

	// SQLite allows only one writer anyway, and a single connection keeps
	// ":memory:" databases intact — every pooled connection would otherwise
	// get its own empty database.
	conn.SetMaxOpenConns(1)

	goose.SetBaseFS(migrations)
	goose.SetLogger(goose.NopLogger())

	if err = goose.SetDialect("sqlite3"); err != nil {
		return nil, err
	}

	if err = goose.Up(conn, "sql/migrations"); err != nil {
		return nil, fmt.Errorf("could not apply migrations: %w", err)
	}

	return &DB{Queries: New(conn), conn: conn}, nil
}

// Close closes the underlying database connection.
func (db *DB) Close() error {
	return db.conn.Close()
}

// Tx runs fn inside a database transaction, committing if fn returns nil and
// rolling back otherwise.
func (db *DB) Tx(ctx context.Context, fn func(q *Queries) error) error {
	tx, err := db.conn.BeginTx(ctx, nil)
	if err != nil {
		return err
	}

	if err := fn(db.Queries.WithTx(tx)); err != nil {
		_ = tx.Rollback()
		return err
	}

	return tx.Commit()
}
