// Package persistence provides access to the lightsql database of moneyd. The
// typed query code is generated by sqlc from internal/persistence/sql; run
// `go generate ./...` after changing the schema or queries.
package persistence

import (
	"context"
	"database/sql"
	"embed"
	"fmt"

	"github.com/pressly/goose/v3"

	lightsql "github.com/oxisto/lightsql/driver"
)

//go:generate sqlc generate -f ../../sqlc.yaml

//go:embed sql/migrations/*.sql
var migrations embed.FS

// DB wraps the generated queries together with the underlying connection.
type DB struct {
	*Queries

	conn *sql.DB
	dsn  string
}

// OpenDB opens the lightsql database at path (a directory, created if
// missing) and applies all pending migrations. Use ":memory:" for an
// ephemeral, in-memory database in tests.
//
// Unlike SQLite, lightsql's in-memory instances aren't private per
// connection: they're just a name, and re-opening one returns whatever a
// previous caller left behind. ":memory:" drops any existing instance under
// that name first, so it keeps SQLite's "always a fresh, isolated database"
// behavior — which every test in this codebase relies on.
func OpenDB(path string) (*DB, error) {
	dsn := "file:" + path
	if path == ":memory:" {
		dsn = path
		lightsql.Drop(dsn)
	}

	conn, err := sql.Open("lightsql", dsn)
	if err != nil {
		return nil, fmt.Errorf("could not open database: %w", err)
	}

	goose.SetBaseFS(migrations)
	goose.SetLogger(goose.NopLogger())

	if err = goose.SetDialect("postgres"); err != nil {
		return nil, err
	}

	if err = goose.Up(conn, "sql/migrations"); err != nil {
		return nil, fmt.Errorf("could not apply migrations: %w", err)
	}

	return &DB{Queries: New(conn), conn: conn, dsn: dsn}, nil
}

// Close closes the underlying database connection. For a directory-backed
// database this also compacts the write-ahead log, so the next OpenDB call
// replays only the rows that survived rather than every change ever made —
// skipping it is safe, just slower to reopen.
func (db *DB) Close() error {
	err := db.conn.Close()
	lightsql.Drop(db.dsn)
	return err
}

// Tx runs fn inside a database transaction, committing if fn returns nil and
// rolling back otherwise.
func (db *DB) Tx(ctx context.Context, fn func(q *Queries) error) error {
	tx, err := db.conn.BeginTx(ctx, nil)
	if err != nil {
		return err
	}

	if err := fn(db.Queries.WithTx(tx)); err != nil {
		_ = tx.Rollback()
		return err
	}

	return tx.Commit()
}
