// Package persistence provides access to the SQLite database of moneyd. The
// typed query code is generated by sqlc from internal/persistence/sql; run
// `go generate ./...` after changing the schema or queries.
package persistence

import (
	"database/sql"
	"embed"
	"fmt"

	"github.com/pressly/goose/v3"
	_ "modernc.org/sqlite"
)

//go:generate sqlc generate -f ../../sqlc.yaml

//go:embed sql/migrations/*.sql
var migrations embed.FS

// DB wraps the generated queries together with the underlying connection.
type DB struct {
	*Queries

	conn *sql.DB
}

// OpenDB opens the SQLite database at path (created if missing) and applies
// all pending migrations. Use ":memory:" for an ephemeral database in tests.
func OpenDB(path string) (*DB, error) {
	conn, err := sql.Open("sqlite", path+"?_pragma=foreign_keys(1)&_pragma=journal_mode(WAL)")
	if err != nil {
		return nil, fmt.Errorf("could not open database: %w", err)
	}

	goose.SetBaseFS(migrations)
	goose.SetLogger(goose.NopLogger())

	if err = goose.SetDialect("sqlite3"); err != nil {
		return nil, err
	}

	if err = goose.Up(conn, "sql/migrations"); err != nil {
		return nil, fmt.Errorf("could not apply migrations: %w", err)
	}

	return &DB{Queries: New(conn), conn: conn}, nil
}

// Close closes the underlying database connection.
func (db *DB) Close() error {
	return db.conn.Close()
}
