// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: portfolios.sql

package persistence

import (
	"context"
)

const createPortfolio = `-- name: CreatePortfolio :one
INSERT INTO
    portfolios (id, person_id, display_name, cash_account_id)
VALUES
    (?, ?, ?, ?) RETURNING id, person_id, display_name, cash_account_id, created_at
`

type CreatePortfolioParams struct {
	ID            string
	PersonID      string
	DisplayName   string
	CashAccountID string
}

func (q *Queries) CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) (*Portfolio, error) {
	row := q.db.QueryRowContext(ctx, createPortfolio,
		arg.ID,
		arg.PersonID,
		arg.DisplayName,
		arg.CashAccountID,
	)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.DisplayName,
		&i.CashAccountID,
		&i.CreatedAt,
	)
	return &i, err
}

const deletePortfolio = `-- name: DeletePortfolio :execrows
DELETE FROM portfolios
WHERE
    id = ?
    AND person_id = ?
`

type DeletePortfolioParams struct {
	ID       string
	PersonID string
}

func (q *Queries) DeletePortfolio(ctx context.Context, arg DeletePortfolioParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePortfolio, arg.ID, arg.PersonID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPortfolio = `-- name: GetPortfolio :one
SELECT
    id, person_id, display_name, cash_account_id, created_at
FROM
    portfolios
WHERE
    id = ?
    AND person_id = ?
`

type GetPortfolioParams struct {
	ID       string
	PersonID string
}

func (q *Queries) GetPortfolio(ctx context.Context, arg GetPortfolioParams) (*Portfolio, error) {
	row := q.db.QueryRowContext(ctx, getPortfolio, arg.ID, arg.PersonID)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.DisplayName,
		&i.CashAccountID,
		&i.CreatedAt,
	)
	return &i, err
}

const listPortfolios = `-- name: ListPortfolios :many
SELECT
    id, person_id, display_name, cash_account_id, created_at
FROM
    portfolios
WHERE
    person_id = ?
ORDER BY
    display_name
`

func (q *Queries) ListPortfolios(ctx context.Context, personID string) ([]*Portfolio, error) {
	rows, err := q.db.QueryContext(ctx, listPortfolios, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Portfolio
	for rows.Next() {
		var i Portfolio
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.DisplayName,
			&i.CashAccountID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePortfolio = `-- name: UpdatePortfolio :one
UPDATE portfolios
SET
    display_name = ?
WHERE
    id = ?
    AND person_id = ? RETURNING id, person_id, display_name, cash_account_id, created_at
`

type UpdatePortfolioParams struct {
	DisplayName string
	ID          string
	PersonID    string
}

func (q *Queries) UpdatePortfolio(ctx context.Context, arg UpdatePortfolioParams) (*Portfolio, error) {
	row := q.db.QueryRowContext(ctx, updatePortfolio, arg.DisplayName, arg.ID, arg.PersonID)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.DisplayName,
		&i.CashAccountID,
		&i.CreatedAt,
	)
	return &i, err
}
