// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: securities.sql

package persistence

import (
	"context"
	"database/sql"
	"time"
)

const createListing = `-- name: CreateListing :one
INSERT INTO
    listings (
        id,
        security_id,
        exchange,
        ticker,
        currency,
        quote_provider
    )
VALUES
    (?, ?, ?, ?, ?, ?) RETURNING id, security_id, exchange, ticker, currency, quote_provider
`

type CreateListingParams struct {
	ID            string
	SecurityID    string
	Exchange      sql.NullString
	Ticker        string
	Currency      string
	QuoteProvider sql.NullString
}

func (q *Queries) CreateListing(ctx context.Context, arg CreateListingParams) (*Listing, error) {
	row := q.db.QueryRowContext(ctx, createListing,
		arg.ID,
		arg.SecurityID,
		arg.Exchange,
		arg.Ticker,
		arg.Currency,
		arg.QuoteProvider,
	)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.SecurityID,
		&i.Exchange,
		&i.Ticker,
		&i.Currency,
		&i.QuoteProvider,
	)
	return &i, err
}

const createQuote = `-- name: CreateQuote :exec
INSERT INTO
    quotes (listing_id, time, price)
VALUES
    (?, ?, ?) ON CONFLICT (listing_id, time) DO
UPDATE
SET
    price = excluded.price
`

type CreateQuoteParams struct {
	ListingID string
	Time      time.Time
	Price     int64
}

func (q *Queries) CreateQuote(ctx context.Context, arg CreateQuoteParams) error {
	_, err := q.db.ExecContext(ctx, createQuote, arg.ListingID, arg.Time, arg.Price)
	return err
}

const createSecurity = `-- name: CreateSecurity :one
INSERT INTO
    securities (id, display_name)
VALUES
    (?, ?) RETURNING id, display_name
`

type CreateSecurityParams struct {
	ID          string
	DisplayName string
}

func (q *Queries) CreateSecurity(ctx context.Context, arg CreateSecurityParams) (*Security, error) {
	row := q.db.QueryRowContext(ctx, createSecurity, arg.ID, arg.DisplayName)
	var i Security
	err := row.Scan(&i.ID, &i.DisplayName)
	return &i, err
}

const createSecurityIdentifier = `-- name: CreateSecurityIdentifier :exec
INSERT INTO
    security_identifiers (security_id, kind, value)
VALUES
    (?, ?, ?)
`

type CreateSecurityIdentifierParams struct {
	SecurityID string
	Kind       string
	Value      string
}

func (q *Queries) CreateSecurityIdentifier(ctx context.Context, arg CreateSecurityIdentifierParams) error {
	_, err := q.db.ExecContext(ctx, createSecurityIdentifier, arg.SecurityID, arg.Kind, arg.Value)
	return err
}

const deleteListings = `-- name: DeleteListings :exec
DELETE FROM listings
WHERE
    security_id = ?
`

func (q *Queries) DeleteListings(ctx context.Context, securityID string) error {
	_, err := q.db.ExecContext(ctx, deleteListings, securityID)
	return err
}

const deleteSecurity = `-- name: DeleteSecurity :execrows
DELETE FROM securities
WHERE
    id = ?
`

func (q *Queries) DeleteSecurity(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSecurity, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSecurityIdentifiers = `-- name: DeleteSecurityIdentifiers :exec
DELETE FROM security_identifiers
WHERE
    security_id = ?
`

func (q *Queries) DeleteSecurityIdentifiers(ctx context.Context, securityID string) error {
	_, err := q.db.ExecContext(ctx, deleteSecurityIdentifiers, securityID)
	return err
}

const findSecurityByIdentifier = `-- name: FindSecurityByIdentifier :one
SELECT
    s.id, s.display_name
FROM
    securities s
    JOIN security_identifiers si ON si.security_id = s.id
WHERE
    si.kind = ?
    AND si.value = ?
`

type FindSecurityByIdentifierParams struct {
	Kind  string
	Value string
}

func (q *Queries) FindSecurityByIdentifier(ctx context.Context, arg FindSecurityByIdentifierParams) (*Security, error) {
	row := q.db.QueryRowContext(ctx, findSecurityByIdentifier, arg.Kind, arg.Value)
	var i Security
	err := row.Scan(&i.ID, &i.DisplayName)
	return &i, err
}

const getLatestQuote = `-- name: GetLatestQuote :one
SELECT
    listing_id, time, price
FROM
    quotes
WHERE
    listing_id = ?
ORDER BY
    time DESC
LIMIT
    1
`

func (q *Queries) GetLatestQuote(ctx context.Context, listingID string) (*Quote, error) {
	row := q.db.QueryRowContext(ctx, getLatestQuote, listingID)
	var i Quote
	err := row.Scan(&i.ListingID, &i.Time, &i.Price)
	return &i, err
}

const getSecurity = `-- name: GetSecurity :one
SELECT
    id, display_name
FROM
    securities
WHERE
    id = ?
`

func (q *Queries) GetSecurity(ctx context.Context, id string) (*Security, error) {
	row := q.db.QueryRowContext(ctx, getSecurity, id)
	var i Security
	err := row.Scan(&i.ID, &i.DisplayName)
	return &i, err
}

const listListings = `-- name: ListListings :many
SELECT
    id, security_id, exchange, ticker, currency, quote_provider
FROM
    listings
WHERE
    security_id = ?
ORDER BY
    ticker
`

func (q *Queries) ListListings(ctx context.Context, securityID string) ([]*Listing, error) {
	rows, err := q.db.QueryContext(ctx, listListings, securityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Listing
	for rows.Next() {
		var i Listing
		if err := rows.Scan(
			&i.ID,
			&i.SecurityID,
			&i.Exchange,
			&i.Ticker,
			&i.Currency,
			&i.QuoteProvider,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuotes = `-- name: ListQuotes :many
SELECT
    listing_id, time, price
FROM
    quotes
WHERE
    listing_id = ?
    AND time >= ?
    AND time <= ?
ORDER BY
    time
`

type ListQuotesParams struct {
	ListingID string
	Time      time.Time
	Time_2    time.Time
}

func (q *Queries) ListQuotes(ctx context.Context, arg ListQuotesParams) ([]*Quote, error) {
	rows, err := q.db.QueryContext(ctx, listQuotes, arg.ListingID, arg.Time, arg.Time_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Quote
	for rows.Next() {
		var i Quote
		if err := rows.Scan(&i.ListingID, &i.Time, &i.Price); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecurities = `-- name: ListSecurities :many
SELECT
    id, display_name
FROM
    securities
ORDER BY
    display_name
`

func (q *Queries) ListSecurities(ctx context.Context) ([]*Security, error) {
	rows, err := q.db.QueryContext(ctx, listSecurities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Security
	for rows.Next() {
		var i Security
		if err := rows.Scan(&i.ID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecurityIdentifiers = `-- name: ListSecurityIdentifiers :many
SELECT
    security_id, kind, value
FROM
    security_identifiers
WHERE
    security_id = ?
ORDER BY
    kind,
    value
`

func (q *Queries) ListSecurityIdentifiers(ctx context.Context, securityID string) ([]*SecurityIdentifier, error) {
	rows, err := q.db.QueryContext(ctx, listSecurityIdentifiers, securityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*SecurityIdentifier
	for rows.Next() {
		var i SecurityIdentifier
		if err := rows.Scan(&i.SecurityID, &i.Kind, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSecurity = `-- name: UpdateSecurity :one
UPDATE securities
SET
    display_name = ?
WHERE
    id = ? RETURNING id, display_name
`

type UpdateSecurityParams struct {
	DisplayName string
	ID          string
}

func (q *Queries) UpdateSecurity(ctx context.Context, arg UpdateSecurityParams) (*Security, error) {
	row := q.db.QueryRowContext(ctx, updateSecurity, arg.DisplayName, arg.ID)
	var i Security
	err := row.Scan(&i.ID, &i.DisplayName)
	return &i, err
}
