// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sessions.sql

package persistence

import (
	"context"
	"database/sql"
	"time"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, expires_at)
VALUES (?, ?, ?)
RETURNING id, user_id, created_at, expires_at, person_id
`

type CreateSessionParams struct {
	ID        string
	UserID    string
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (*Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.ID, arg.UserID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.PersonID,
	)
	return &i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, created_at, expires_at, person_id
FROM sessions
WHERE id = ? AND expires_at > now()
`

func (q *Queries) GetSession(ctx context.Context, id string) (*Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.PersonID,
	)
	return &i, err
}

const updateSessionPerson = `-- name: UpdateSessionPerson :exec
UPDATE sessions SET person_id = ? WHERE id = ?
`

type UpdateSessionPersonParams struct {
	PersonID sql.NullString
	ID       string
}

func (q *Queries) UpdateSessionPerson(ctx context.Context, arg UpdateSessionPersonParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionPerson, arg.PersonID, arg.ID)
	return err
}
