// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package persistence

import (
	"context"
	"database/sql"
	"time"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO
    transactions (
        id,
        type,
        time,
        portfolio_id,
        security_id,
        cash_account_id,
        units,
        price,
        fees,
        taxes,
        cash_delta,
        currency,
        source
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, type, time, portfolio_id, security_id, cash_account_id, units, price, fees, taxes, cash_delta, currency, source, created_at
`

type CreateTransactionParams struct {
	ID            string
	Type          string
	Time          time.Time
	PortfolioID   sql.NullString
	SecurityID    sql.NullString
	CashAccountID sql.NullString
	Units         float64
	Price         sql.NullInt64
	Fees          int64
	Taxes         int64
	CashDelta     int64
	Currency      string
	Source        string
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (*Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.ID,
		arg.Type,
		arg.Time,
		arg.PortfolioID,
		arg.SecurityID,
		arg.CashAccountID,
		arg.Units,
		arg.Price,
		arg.Fees,
		arg.Taxes,
		arg.CashDelta,
		arg.Currency,
		arg.Source,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Time,
		&i.PortfolioID,
		&i.SecurityID,
		&i.CashAccountID,
		&i.Units,
		&i.Price,
		&i.Fees,
		&i.Taxes,
		&i.CashDelta,
		&i.Currency,
		&i.Source,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteTransaction = `-- name: DeleteTransaction :execrows
DELETE FROM transactions
WHERE
    id = ?
`

func (q *Queries) DeleteTransaction(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTransaction, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTransaction = `-- name: GetTransaction :one
SELECT
    id, type, time, portfolio_id, security_id, cash_account_id, units, price, fees, taxes, cash_delta, currency, source, created_at
FROM
    transactions
WHERE
    id = ?
`

func (q *Queries) GetTransaction(ctx context.Context, id string) (*Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Time,
		&i.PortfolioID,
		&i.SecurityID,
		&i.CashAccountID,
		&i.Units,
		&i.Price,
		&i.Fees,
		&i.Taxes,
		&i.CashDelta,
		&i.Currency,
		&i.Source,
		&i.CreatedAt,
	)
	return &i, err
}

const listTransactionsByCashAccount = `-- name: ListTransactionsByCashAccount :many
SELECT
    id, type, time, portfolio_id, security_id, cash_account_id, units, price, fees, taxes, cash_delta, currency, source, created_at
FROM
    transactions
WHERE
    cash_account_id = ?
ORDER BY
    time
`

func (q *Queries) ListTransactionsByCashAccount(ctx context.Context, cashAccountID sql.NullString) ([]*Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByCashAccount, cashAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Time,
			&i.PortfolioID,
			&i.SecurityID,
			&i.CashAccountID,
			&i.Units,
			&i.Price,
			&i.Fees,
			&i.Taxes,
			&i.CashDelta,
			&i.Currency,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByPortfolio = `-- name: ListTransactionsByPortfolio :many
SELECT
    id, type, time, portfolio_id, security_id, cash_account_id, units, price, fees, taxes, cash_delta, currency, source, created_at
FROM
    transactions
WHERE
    portfolio_id = ?
ORDER BY
    time
`

func (q *Queries) ListTransactionsByPortfolio(ctx context.Context, portfolioID sql.NullString) ([]*Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByPortfolio, portfolioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Time,
			&i.PortfolioID,
			&i.SecurityID,
			&i.CashAccountID,
			&i.Units,
			&i.Price,
			&i.Fees,
			&i.Taxes,
			&i.CashDelta,
			&i.Currency,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET
    type = ?,
    time = ?,
    portfolio_id = ?,
    security_id = ?,
    cash_account_id = ?,
    units = ?,
    price = ?,
    fees = ?,
    taxes = ?,
    cash_delta = ?,
    currency = ?
WHERE
    id = ? RETURNING id, type, time, portfolio_id, security_id, cash_account_id, units, price, fees, taxes, cash_delta, currency, source, created_at
`

type UpdateTransactionParams struct {
	Type          string
	Time          time.Time
	PortfolioID   sql.NullString
	SecurityID    sql.NullString
	CashAccountID sql.NullString
	Units         float64
	Price         sql.NullInt64
	Fees          int64
	Taxes         int64
	CashDelta     int64
	Currency      string
	ID            string
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (*Transaction, error) {
	row := q.db.QueryRowContext(ctx, updateTransaction,
		arg.Type,
		arg.Time,
		arg.PortfolioID,
		arg.SecurityID,
		arg.CashAccountID,
		arg.Units,
		arg.Price,
		arg.Fees,
		arg.Taxes,
		arg.CashDelta,
		arg.Currency,
		arg.ID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Time,
		&i.PortfolioID,
		&i.SecurityID,
		&i.CashAccountID,
		&i.Units,
		&i.Price,
		&i.Fees,
		&i.Taxes,
		&i.CashDelta,
		&i.Currency,
		&i.Source,
		&i.CreatedAt,
	)
	return &i, err
}
