// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package persistence

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (id, issuer, subject, display_name)
VALUES
    (?, ?, ?, ?) RETURNING id, issuer, subject, display_name, created_at
`

type CreateUserParams struct {
	ID          string
	Issuer      string
	Subject     string
	DisplayName string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Issuer,
		arg.Subject,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Issuer,
		&i.Subject,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return &i, err
}

const getUser = `-- name: GetUser :one
SELECT
    id, issuer, subject, display_name, created_at
FROM
    users
WHERE
    id = ?
`

func (q *Queries) GetUser(ctx context.Context, id string) (*User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Issuer,
		&i.Subject,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return &i, err
}

const getUserByIdentity = `-- name: GetUserByIdentity :one
SELECT
    id, issuer, subject, display_name, created_at
FROM
    users
WHERE
    issuer = ?
    AND subject = ?
`

type GetUserByIdentityParams struct {
	Issuer  string
	Subject string
}

func (q *Queries) GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (*User, error) {
	row := q.db.QueryRowContext(ctx, getUserByIdentity, arg.Issuer, arg.Subject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Issuer,
		&i.Subject,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return &i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
    id, issuer, subject, display_name, created_at
FROM
    users
ORDER BY
    display_name
`

func (q *Queries) ListUsers(ctx context.Context) ([]*User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Issuer,
			&i.Subject,
			&i.DisplayName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
