// Code generated by "stringer -linecomment -type=PortfolioEventType -output=type_string.go"; DO NOT EDIT.

package events

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PortfolioEventTypeBuy-1]
	_ = x[PortfolioEventTypeSell-2]
	_ = x[PortfolioEventTypeDividend-3]
	_ = x[PortfolioEventTypeDeliveryInbound-4]
	_ = x[PortfolioEventTypeDeliveryOutbound-5]
	_ = x[PortfolioEventTypeDepositCash-6]
	_ = x[PortfolioEventTypeWithdrawCash-7]
	_ = x[PortfolioEventTypeUnknown-8]
}

const _PortfolioEventType_name = "BUYSELLDIVIDENDDELIVERY_INBOUNDDELIVERY_OUTBOUNDDEPOSIT_CASHWITHDRAW_CASHUNKNOWN"

var _PortfolioEventType_index = [...]uint8{0, 3, 7, 15, 31, 48, 60, 73, 80}

func (i PortfolioEventType) String() string {
	i -= 1
	if i < 0 || i >= PortfolioEventType(len(_PortfolioEventType_index)-1) {
		return "PortfolioEventType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PortfolioEventType_name[_PortfolioEventType_index[i]:_PortfolioEventType_index[i+1]]
}
