// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ListedSecurityInput struct {
	Ticker   string `json:"ticker"`
	Currency string `json:"currency"`
}

type Mutation struct {
}

type Query struct {
}

type SecurityInput struct {
	ID          string                 `json:"id"`
	DisplayName string                 `json:"displayName"`
	ListedAs    []*ListedSecurityInput `json:"listedAs,omitempty"`
}
