// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewSecurity struct {
	ID          string `json:"id"`
	DisplayName string `json:"displayName"`
}

type Query struct {
}
