// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewSecurity struct {
	Isin        string `json:"isin"`
	DisplayName string `json:"displayName"`
}

type Query struct {
}
