name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: "**/*.sum"
      - name: Set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
      - name: Set up buf
        uses: bufbuild/buf-setup-action@v1.48.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up tools
        run: |
          go install github.com/mfridman/tparse
          go install github.com/sqlc-dev/sqlc/cmd/sqlc
          go install github.com/99designs/gqlgen
        working-directory: ./tools
      - name: Build Backend
        run: |
          go generate ./...
          go build -v ./...
      - name: Test Backend
        run: |
          go test -v -coverprofile=coverage.cov -coverpkg ./... -covermode=atomic ./...  -json | tee output.json | tparse -follow || true
          tparse -format markdown -file output.json > $GITHUB_STEP_SUMMARY
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.cov
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Build UI
        run: |
          npm ci
          npm run build
        working-directory: ./ui
