name: Add issues to development project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.6.1
        with:
          project-url: https://github.com/users/oxisto/projects/2
          github-token: ${{ secrets.PAT }}
          labeled: dependencies
          label-operator: NOT
